// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjoudjqchlptotwvesls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indqb3VkanFjaGxwdG90d3Zlc2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxNTg0MjEsImV4cCI6MjA4NTczNDQyMX0._pIXmgqKFFofvzoEXx77prHt5ga3HDWbEvkdgqOxLb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});